import axios from 'axios';

    const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
      
    const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
      
    const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';